- lib/cloudregister/registerutils.py
- usr/sbin/registercloudguest
+ This will be needed for use in zypper plugins to transmit instance
data during zypper requests
> - Re-factor code to make instance data collection re-usable

- cloud-regionsrv-client.spec
See [bsc#1152567](https://bugzilla.suse.com/show_bug.cgi?id=1152567)
> Include python3-six in dependencies (bsc#1152567)

- lib/cloudregister/registerutils.py
+ When registercloudguest was used to clean the system the registration
was not removed from the server. WIth this change the registration will
be removed from the server allowing us to easily pass the information
to SCC in cases where the instances is a BYOS instance that uses the
update infrastructure. This ensures accurate tracking of subscriptions.
> - Remove system record from server upon clean

- lib/cloudregister/amazonec2.py
+ Properly return the region id for local zones and "regular" availability
zones to extract the region information as the region hint.
> - AWS handle local zones

- cloud-regionsrv-client.spec
- usr/sbin/regionsrv-enabler-azure
> Do not run registercloudguest if no AHB

- lib/cloudregister/registerutils.py
- Remove method check_registration, as
is_registered called that and both
have the same logic
Implementation uses is_registered
and behavior/workflow should remain
the same
> Refactor is_registered method

- cloud-regionsrv-client.spec
- lib/cloudregister/msftazure.py
- tests/test_azureplugin.py
> Lowercase MSFT region hints

- usr/sbin/registercloudguest
- Show registration status in console
This Fixes bsc#1197113
> Add status registration message

- cloud-regionsrv-client.spec
- lib/cloudregister/registerutils.py
- usr/sbin/regionsrv-enabler-azure
- Cache the license type to track PAYG license switch to PAYG license
- Bump version
> Add license cache

- usr/sbin/regionsrv-enabler-azure
Update license cache if no file
instead of stating there has been a change
> Update license change

- cloud-regionsrv-client.spec
- usr/lib/zypp/plugins/urlresolver/susepubcloud
> Rename susecloud plugin

- cloud-regionsrv-client.spec
> Conflict with container-suseconnect

- lib/cloudregister/amazonec2.py
- lib/cloudregister/registerutils.py
- man/man1/registercloudguest.1
During the review of Robert's PR I spotted some typos and flake8 issues in some other parts of the code.
> Fix typos and flake8 issues

- tests/test_smt.py
> Fix test that was passing because of a typo :open_mouth: 

- cloud-regionsrv-client.spec
- usr/sbin/createregioninfo
- usr/sbin/registercloudguest
We are going to depend on the region info cache file for vwraious conditions. Therefore we have to make sure it exists. Create the file when the package gets updated.
> Create region info on package update

- lib/cloudregister/registerutils.py
Move the code to a function to eliminate code duplication.
> Refactor the extraction of the system information

- lib/cloudregister/registerutils.py
I spotted some parts in the utils file that could be improved with the use context managers.
> Includes context managers for file management in utils

- usr/sbin/registercloudguest
With IPv6 being enabled, better check the input is OK
> Validate IP address

- usr/sbin/registercloudguest
> Rename registration_returncode to registration_failed

- lib/cloudregister/registerutils.py
- tests/test_registerutils.py
Little too strict check so a better guard clause
> Better no valid credentials check

- .gitignore
- .virtualenv.dev-requirements.txt
- .virtualenv.requirements.txt
- lib/cloudregister/amazonec2.py
- lib/cloudregister/registerutils.py
- lib/cloudregister/smt.py
- tests/test_ec2plugin.py
- tox.ini
This change aims to add automated tests and checks on the project
- Add tox.ini
- Add env requirements
- Add .gitignore
- Fix code
- Fix tests
> Added tox.ini and fix tests

- .github/workflows/ci-testing.yml
- lib/cloudregister/amazonec2.py
- lib/cloudregister/registerutils.py
- tests/test_azureplugin.py
- tests/test_ec2plugin.py
- tests/test_gceplugin.py
- tests/test_registerutils.py
- tests/test_smt.py
- tox.ini
- Add tests to flake8 check
- Update tests
- Update registerutils
> Add tests for flake8 check

- tests/test_azureplugin.py
- tests/test_ec2plugin.py
- tests/test_gceplugin.py
- tests/test_registerutils.py
- tests/test_smt.py
> don't depend on the external plugin mock and use unittest.mock only

- .virtualenv.requirements.txt
- lib/cloudregister/registerutils.py
- tests/data/registry_conf.conf
- tests/data/unconfigured_registry.conf
- tests/test_registerutils.py
- Add registries conf registry content
- Remove registries conf registry content
> Handle search order for the registry

- .virtualenv.requirements.txt
- lib/cloudregister/registerutils.py
- tests/test_registerutils.py
- Add SUSE registry FQDN to the SUMA if not present
> Handle SUMA registry file

- lib/cloudregister/registerutils.py
- tests/test_registerutils.py
- Get the smt registry FQDN one time, if present
> Remove getting smt registry FQDN duplicates

- lib/cloudregister/registerutils.py
instead of piggyback on the for-loop
> Move the registry.suse.com check back to the original approach

- lib/cloudregister/registerutils.py
- usr/sbin/registercloudguest
Re adding the call in registercloudguest
> Add the call to set up the registry

- tox.ini
- usr/bin/cloudguestregistryauth
- usr/etc/sudoers.d/cloudguestregistryauth
- Remove local from sudoers content path
- Call command with 'usod' prefix if not sudo
> Proper sudo call

- .github/workflows/ci-testing.yml
- setup.cfg
- tox.ini
Make sure we test our code also against python version 3.11 which has landed in SLES too. Also fix the tox setup as well as add a proper pytest config and add one missing test for the code path if no network connection is possible.
> Update and extend test matrix

- cloud-regionsrv-client.spec
There is code that imports the yaml module but no
package requirement is setup in the spec file
> Fix spec file

- lib/cloudregister/registerutils.py
- setup.cfg
- tests/data/hosts
- tests/data/some_env
- tests/data/some_invalid_env
- tests/test_registerutils.py
- tox.ini
- usr/sbin/registercloudguest
This patch is two fold
**Fix a missing exit condition**
In case an alternative update server was found and the system is properly registered there is not more to do. We found this over a conversation with Robert and I thought let's fix it here
**Update the container registry code path**
Change the code that runs the container registry registration process  to check if the registry has already been setup. At the moment  there is no check and the only reason why it's not called multiple times are the early exit conditions which we have
to modify for the LTSS use cases.
This is in line with the dev plan as one of the first actions to prepare the code such that we can add the LTSS required additional code without causing too many bad after effects
The show can begin ;)
> Preparation for ltss

- usr/sbin/registercloudguest
- Move the block to get the instance data written in a file to before LTSS block
- Update the methods to incude instance data file path
> Send instance data when activating LTSS

- usr/sbin/registercloudguest
use SLES-LTSS instead of sles-LTSS,for example
> Do not lower the product name text

- usr/sbin/registercloudguest
- Print if LTSS activation succeeded, failed or already registered
> Inform the user in the CLI (as it is informed in the log) about LTSS status messages

- integration_test-process.txt
Include tests for LTSS and update processes to check registry access and configuration.
> Update integration test process

- cloud-regionsrv-client.changes
This patch is two fold
**Add changes file to git**
Add cloud-regionsrv-client.changes file to the git for consistent changelog review and submission to targets
**Add changelog entry for the latest spec change**
For details see #209
> Add changelog to git

- lib/cloudregister/registerutils.py
- tests/test_registercloudguest.py
- tests/test_registerutils.py
We have a number of state files that get added and removed based on the state and progress of registration or based on billing model. Each of these had it's own implementation for creating and removing the state file. Create a utility functions to create and remove a state file and change the existing code to use the new functions.
> Refactor state file setting
