SUSE-Enceladus/cloud-regionsrv-client

- lib/cloudregister/registerutils.py
Currently services/repos aren't being removed when `registercloudguest --force-new` is invoked. [RMT returns URLs](https://github.com/SUSE/rmt/blob/d1f1000ab099154a4243f123277ff3259be8c130/engines/zypper_auth/lib/zypper_auth/engine.rb#L59) in `plugin:/susecloud` format, rather than `plugin:susecloud`.
> Fix removal of services/repos during cleanup

- lib/cloudregister/registerutils.py
Closes #8 
The plugin links were treated as INI files thus causing a parser error. This broke the '--forec-new' functionality
> Avoid parse error

- cloud-regionsrv-client.spec
```
(W) found COPYING or LICENSE file marked as %doc, please mark as %license instead
LINE is: "%doc README LICENSE"
```
> Use %license macro in specfile

- lib/cloudregister/registerutils.py
- usr/lib/zypp/plugins/urlresolver/susecloud
This is a suggested fix to issue #20 
Since the plugin is run on every url resolution the check can be made only for the specific credential file corresponding to the repo being validated. This avoids accidental checks of other private repo credential files
> intial suggestion

- usr/sbin/registercloudguest
The HTTP response reason is too generic and doesn't help identify the root cause of registration issues. This change adds the response content from the SMT server to expose the underlying issue.
Example issue (easily reproducible):
1. Change the symlink of the baseproduct symlink to anything other than the main SLES product in /etc/products.d (sudo ln -sfn sle-module-toolchain.prod baseproduct)
2. run sudo registercloudguest --force-new
3. you'll find a generic error in cloudregister logs:
```
2020-05-19 04:49:14,009 ERROR:Unable to obtain product information from server "[SMT target server IP],None"
Unprocessable Entity
Unable to register modules, exiting.
```
This is masking the underlying error that we actually get from the SMT response's content:
```
b'{"type":"error","error":"Unmet …
```
> Expose SMT response on registration failure

- cloud-regionsrv-client.spec
- usr/lib/systemd/system/containerbuild-regionsrv.service
- usr/sbin/containerbuild-regionsrv
This provides a small service can be used by container building tools like "docker" or "podman build" to obtain the required info for being able to install packages inside the container image using the Public Cloud RMTs. It is susposed to be used in conjunction with "container-suseconnect" when building images inside on-demand public cloud instances.
This goes together with a couple of changes in container-suseconnect which we're currently finalizing in https://github.com/SUSE/container-suseconnect/tree/new-authentication-scheme.
> Introduce containerbuild-regionsrv service

- usr/sbin/containerbuild-regionsrv
The Python release available on SLE12 (3.4.x) does not support the
"context manager" protocol. Rework the code to something backwards
compatible.
Closes #36
> Fix containerbuild-regionsrv for SLE12

- lib/cloudregister/registerutils.py
does not exists
+ It is possible the system is set up to source proxy environment variable
settings from a non standard location and we should honor the environment
settings no matter how they got there.
- Closes #38
> - Consider the proxy environment settings even if the configuration file

- usr/sbin/registercloudguest
+ As a hold over from SMT and SMT registration script we were parsing
the return string to detect an error condition. SUSEConnect sets an error
code thus we should use it to be a more reliable detector for registration
errors.
> - Use the return code of SUSEConnect to detect errors

- lib/cloudregister/registerutils.py
- usr/sbin/registercloudguest
Currently registercloudguest command doesn't read NO_PROXY from /etc/sysconfig/proxy file.  This will cause EC2 metadata requests being sent to proxy despite NO_PROXY configuration exist in the proxy config file to bypass proxy for EC2 metadata requests. Reading NO_PROXY from the proxy config file and set it to the environment should fix this issue.
> Add support for no_proxy env variable

- cloud-regionsrv-client.spec
- usr/lib/systemd/system/regionsrv-enabler.service
- usr/lib/systemd/system/regionsrv-enabler.timer
- usr/sbin/regionsrv-enabler
A package running with a timer to enable/disable
the access to the infrastructure from Azure instances.
If running instance is MSFT and the license type
is BYOS, guestregister service is not enable and
the infra repositories are not available.
This references bsc#1182026
> New package to enable/disable access due to AHB

- etc/regionserverclnt.cfg
- lib/cloudregister/registerutils.py
- tests/test_registerutils.py
- usr/sbin/registercloudguest
Added util method is_registration_supported() which checks
if a registration process is available based on the supported
package manager backend. This change helps to configure the
behavior of registercloudguest on non SUSE based products.
Product families for which there is no subscription/registration process available will
exit after the repository hosts setup from registercloudguest
> Added registration availability check

- lib/cloudregister/registerutils.py
+ Region servers can be configured with a DNS resolvable name. The current
code assumed address based access only. This change handles region servers
with DNS names. In a situation where region servers are specified as a
mix of IP addresses and DNS names the servers with DNS names are at
the end of the lookup list.
> - Region servers can have a DNS resolvable name

- lib/cloudregister/registerutils.py
+ During initial registration against a specific server credential access
is probed triggering an error in the log file. However, during first
registration we expect to have no credentials and as such no error
should be reported
> - Do not report false positives for credential access

- cloud-regionsrv-client.spec
- lib/cloudregister/msftazure.py
- tests/test_azureplugin.py
- tests/test_registerutils.py
- usr/sbin/regionsrv-enabler-azure
The interface for is_registered expects a string of the FQDN for the update server, it no longer takes and object
> Adapt to interface changes for is_registered()

- lib/cloudregister/registerutils.py
+ When a instance data provider is configured but the collected data is
empty it is highly likely that registration will fail. Provide a warning
message indicating the data collection issue.
> Provide warning message on empty metadata

- usr/lib/systemd/system/regionsrv-enabler-azure.timer
+ The enabler for the repos is an independent service and must remain
independent such that the registration can be enabled in code under the
pre-determined conditions.
> Remvoe enabler dependency on the registration service

- lib/cloudregister/registerutils.py
- Problem: When running registercloudguest --clean in a
BYOS instance, some credentials were not removed
- No need to separate PAYG cleaning credentials with BYOS
- Add service value to the list for removing credentials,
this works because the service value is the name of the
credential file in PAYG and BYOS
> Update clean credentials

- cloud-regionsrv-client.spec
- While the code was updated for the read-only root setup of SLE-Micro the
spec file was not updated to accomodate the new locations for the cache
that is needed by cloud-regionsrv-client and the generic config was not
updated for the cert location of region server certs. This update addresses
the problem introduced with 531d162a2cfb
> Fixes for ro root

- lib/cloudregister/registerutils.py
zypper may have different process table name entries, "zypper" and "Zypp-main" depending on the zypper version. We need to handle both names in order to know if we are in the same process or not to shortcut some tests.
> zypper name change

- lib/cloudregister/registerutils.py
- tests/test_registerutils.py
- usr/lib/zypp/plugins/urlresolver/susecloud
- At present when an update server has a cert change the client will fail and the user has to force a re-registration in order to get the new cert onto the client system. This change makes the import of the new cert automatic. A cert check is run every time zypper is executed.
- Improve test coverage of the utils code
> Handle update server cert change

- lib/cloudregister/msftazure.py
- tests/test_azureplugin.py
- tests/test_ec2plugin.py
- tests/test_gceplugin.py
- tests/test_registerutils.py
Pending PR to remove some unused imports and remove some pending flake8 issues.
After this PR is merged, the only errors for flake8 are:
```
flake8 tests/ lib/
tests/test_azureplugin.py:27:1: E402 module level import not at top of file
tests/test_ec2plugin.py:27:1: E402 module level import not at top of file
tests/test_gceplugin.py:27:1: E402 module level import not at top of file
tests/test_registerutils.py:28:1: E402 module level import not at top of file
tests/test_smt.py:28:1: E402 module level import not at top of file
lib/cloudregister/registerutils.py:544:22: W605 invalid escape sequence '\s'
lib/cloudregister/registerutils.py:545:22: W605 invalid escape sequence '\s'
lib/cloudregister/registerutils.py:546:20: W605 invalid escape sequence '\s' …
```
> Removes unused imports and other flake8 errors

- lib/cloudregister/registerutils.py
- tests/data/framework_info
- tests/test_registerutils.py
- usr/sbin/registercloudguest
Switch the region change detaction over from using cached update server data to using the new region information file. This allows us to handle cert changes of the update servers in a cleaner way. Previously a cert change on an update server would have triggered the new region detection path unnecessarily.
> Refactor the way we detect a region change

- lib/cloudregister/registerutils.py
- lib/cloudregister/smt.py
- tests/test_registerutils.py
- tests/test_smt.py
- usr/lib/zypp/plugins/urlresolver/susecloud
- usr/sbin/registercloudguest
- usr/sbin/updatesmtcache
Detect if the cert of the current target update server has changed. If it has update the client system by importing the new cert. Also check the hosts entry and update if necessary.
> Handle cert changes

- lib/cloudregister/registerutils.py
Before systems registered either to SCC
or RMT infrastructure, now there can be
cases where the cleaning up needs to
happen for both type of repositories
> Remove from SCC when cleaning up

- lib/cloudregister/registerutils.py
-- SCC uses system_token for duplicate systems 
and as such, SCC writes the system_token value 
in the credentials file, versions newer than 0.3.36 
will not write the system_token 
Regardless, cloud-regionsrv-client only checks 
username and password in the credentials file so, 
code ignores (does not show a warning) if system_token 
entry is present
> Do not warn about system_token entry

- Makefile
Makes sure the following files are not included when creating the tar with the Makefile:
- __pycache__ directory
- *.pyc files
- *.pyo files
- cloudregister.egg-info directory
> Includes some statements to assure some python cache files are not included in the tar file

- usr/sbin/registercloudguest
- Log a message when the user initiates a registration clean up with --clean. Fixes #117
- If baseproduct registration fails call cleanup, otherwise the SCCCredentials file is left behind an dthe system is not left in a prestine state.
> Clean up and logging

- lib/cloudregister/smt.py
- tests/test_smt.py
At present when an IPv6 address is present in the configuration received from the region server but the client network has no ipv6 capabilities the detection if he server is responsive fails as the ipv4 access is not checked. This update expands the code to check access via ipv4 shold the ipv6 access fail.
> Server access testing expansion

- cloud-regionsrv-client.spec
This is the start of being able to use cloud-regionsrv-client from a container. Inside a container we do not want systemd and it's dependencies. Change the macro used such that systemd is not automatically set up as package dependency on SLE 15 and later distributions.
> Prep for container use

- usr/sbin/registercloudguest
If the instance has extra modules activated before running registercloudguest command, we should register the instance and inform the user about those extra modules not installed and how to install them
Fixes bsc#1215198
> Handle extra extensions or modules when registering

- usr/sbin/registercloudguest
Currently, if registration failed, the command registercloudguest would return 0 as its return code on some scenarios 
This PR should fix that
Remove cache file before informing if registration failed (and exit) or not
> Report error when registration failed

- lib/cloudregister/smt.py
- tests/test_smt.py
When the region server returns an update server configuration with IPv4 and IPv6 but the client only has IPv4 capability an unhandeld exception is triggered due to an uninitialized variable.
Once the unitialized variable issue is fixed, the code will write the server cert to the trust anchors only with the IPv6 name as reference. This is confusing. The updated code writes the cert with botht the IPv4 and IPv6 names.
Add tests for the updates smt.py implementation.
> Unhandeled Exception with IPv4 only client with IPv6 update server config

- cloud-regionsrv-client.spec
- lib/cloudregister/amazonec2.py
- tests/test_ec2plugin.py
The algorithm computing the region hint from the availability zone data retrieved from IMDS did not take into account that there may be a longer prefix before the AZ indicator. This changes implements a variable length search algorithm.
> Fix region computation

- lib/cloudregister/registerutils.py
- tests/test_registerutils.py
In the case of no credentials present,
the check of credentials should not generate
an exception
> Add handling case when no credentials present

- etc/regionserverclnt.cfg
- integration_test-process.txt
- tests/data/regionserverclnt.cfg
- usr/sbin/registercloudguest
Update regionserverclnt.cfg with new certLocation i.e. /usr/lib/regionService/certs and address some minor typos.
> Update regionserverclnt.cfg with new cert path

- lib/cloudregister/registerutils.py
- lib/cloudregister/smt.py
In order to check whether a RMT server is responsive, a https request is triggered with verification disable making the request to show a warning
This PR silences that warning
> Disable insecure request warning

- lib/cloudregister/registerutils.py
- tests/test_registerutils.py
The current implementation to point tools like docker, podman, etc to our infrastructure registry is based on exporting a number of environment variables which are read by the individual tools. The file written so far was placed to ```/etc/bash.bashrc.local```. However, there is no mechanism in the system which would automatically source this file on a new login. So far only the console which has started registercloudguest or the respective service at boot time has the right environment set up. This commit changes the location of the env file to ```/etc/profile.local```. This is a system wide profile file for custom settings in addition to /etc/profile. The file is automatically sourced on every login or ssh login which allows us to make sure our settings are active in every login session …
> Refactor profile reading

- usr/sbin/registercloudguest
For systems that are already registered we do not want to force the user to re-register the system to get access to the registries. When we detect, on boot or manual execution that the system already points to the update infrastructure add the registry setup to the system.
> Add registry to already registered systems

- usr/sbin/registercloudguest
Update early exit condition and registry setup
* Reduce code duplication and prevent duplicate checking for  utils.is_registry_registered, increase readability and prepare better for the LTSS use case additions in the future
* Refactor code to identify the responding update servers into its own function for better readibility.
* Move the setup of the container registry in front of the setup of the repositories(SUSEConnect), as it could now be done directly after checking of the early exit condition
> Update early exit condition and registry setup

- usr/sbin/registercloudguest
Instead of duplicating the code to prepare for a SUSEConnect (or the respective transactional) command, provide a common method named run_SUSEConnect which only receives the relevant parameters. Apply the new method to the main registration call as well as to the module registration. This refactor was done also in preparation to an additional LTSS regcode process which requires another SUSEConnect call.
> Deduplicate code that calls SUSEConnect

- usr/sbin/registercloudguest
Add method setup_ltss_registration which is called if a registration code is provided and the instance has been registered properly.
This change has been integration tested in my development environment as follows
```
[ OK  ] Started Command Scheduler.
Starting Obtain Cloud update server info and register with the server...
...
Welcome to SUSE Linux Enterprise Server 15 SP5  (x86_64) - Kernel 5.14.21-150500.55.65-default (console).
==> login
==> zypper refresh
```
```
registercloudguest --regcode 123456
Registering system to registration proxy https://localhost:44300
Updating system details on https://localhost:44300 ...
Activating sles 15.5 x86_64 ...
Error: Registration server returned 'No subscription with this Registration Code found' (422)
==> log file contents
2024-08-01 …
```
> Add LTSS registration

- cloud-regionsrv-client.spec
- fix-for-sles12-disable-ipv6.patch
- fix-for-sles12-disable-registry.patch
For SLE12 some patches to the registration client are needed. I moved the existing patch to the git and also added a new one which we need because we don't support the registry registration on SLE12
> Sle12 ports

- usr/sbin/registercloudguest
As part of the LTSS changes in the registration client the initial setup of the registry moved before the base product setup. This was considered not an issue but it is one. That's because the setup of the registry reads the RMT credentials from /etc/zypp/credentials.d/SCCcredentials which only exists after the initial base product registration. This means the initial registry setup has to follow the initial base product registration. This commit fixes it
> Fix sequence order for initial registry setup

- integration_test-process.txt
Those commands use the same method that registry engine uses on RMT to verify cache access, so they must work as expected
> Add SUSEConnect command for testing

- lib/cloudregister/registerutils.py
- tests/data/hosts
- tests/test_registerutils.py
- usr/sbin/registercloudguest
There is a logic error in the code that sets up the hosts entry. One method named add_hosts_entry() is responsible for setting up the RMT and the registry hosts entries. Both entries targets the same server IP and can only be differentiated by their name and not by their IP. Next to this design there is a method named has_rmt_in_hosts() which checks by the IP of the server if the hosts entry exists or not. Obviously this condition check is not sufficient if there is the need to check individually for the hosts entry of the RMT target or the registry target.
At the time we added support for the container registry target, we require a more specific host entry checking which is specific to the target system we want to add the hosts entry for. This is because there are instances which can run …
> Fixed setup of registry hosts entry

- integration_test-process.txt
- lib/cloudregister/registerutils.py
- tests/test_registerutils.py
Per docker documentation setting a registry mirror requires a url. Previously we wrote the fqdn of the update server to the daemon.json which breaks docker daemon start up with the 'unsupported scheme "" ' message. Convert the fqdn into a url.
> Fix docker config file mirror settings

- integration_test-process.txt
- lib/cloudregister/registerutils.py
- tests/test_registerutils.py
During migration the various process get spawned. When looking for the main zypper executable (Zypp-main) we also get information about the child process. However we are only interested in the main process PID. Change the logic to extract the PID such the we only look at the PID for the main process.
> Handle process structure change

- usr/sbin/registercloudguest
Do not check for the instance metadata file at the point of call, this is already handled by the function implementation.
Only create the instance metadata file if we have instance metadata to write, this ensures we do not create an empty file that then gets passed to downstream invocations hoping that the downstream code copes properly with an empty file.
> Remove superfluous condition

- lib/cloudregister/registerutils.py
- tests/test_registerutils.py
- usr/sbin/registercloudguest
At present when we test for network access by IP protocol version the message in the log file makes it hard to differentiate whether this is hard error or for information. While the message is set as info it still contains the word "error" in the message. Make the message less alarming in an attempt to not train users to ignore errors.
Enhance the testing of the function checking the network access. Previously only the happy path was tested.
Make the network acces test function private to the utils, we do not want function to be used outside the utils. Client code should use the test methods for IPv4 and IPv6 access.
> Make network access check message less alarming

- usr/sbin/registercloudguest
The LTSS registration take a bit longer as such we want the user to know that we are doing something. Print a message to give the user some confidence that we are doing something useful.
> LTSS registration user message

- cloud-regionsrv-client.spec
- fix-for-sles12-no-trans_update.patch
- The way Python is being built has changed for SUSE distributions. Python 3.6 is, by design no longer available in products SLE Micro and later. We need to use macros that are defined in the build service to pick up the interpreter we want to use for building our code and to find the proper Python module packages we depend on.
- Add a previoulsy forgotten patch for the SLE 12 build that we need to maintain until the EOL of that code stream.
> package build update

- lib/cloudregister/registerutils.py
- tests/test_registercloudguest.py
- tox.ini
- usr/sbin/registercloudguest
It happens (and it has happened) that some errors/bugs come from registercloudguest due to
either missing things or having things not correctly set which would get caught if registercloudguest had tests
Some corrections were done (each of them has its own commit) even in this PR as they were found during the tests addition
This PR aims to reduce the amount of missing things in this project
- Modify registercloudguest to call main()
- Add tests to registercloudguest
- Add a check to keep the coverage for registercloudguest at 100%
- Add linter check for registercloudguest
> Registercloudguest coverage

- lib/cloudregister/registerutils.py
- tests/test_registerutils.py
This patch is many fold and the result of testing our registry setup and cleanup. I found the following defects while testing:
1. There is an index comparison issue at setup of the podman and docker registry files, which leads to duplicate entries if the first element is registry.suse.com
2. The cleanup method deletes files that belongs to the `libcontainers-common` package and that deletion drops more information than just the registry search path which will then never be restored.
3. If a user creates manual changes on the registry search path that are **not** related to our private registry path (which must  be first) we still change the order of entries in our registration process. This is an unexpected and also unwanted behavior
4. Overall the implementation for setup and cleanup …
> Fix setup of unqualified search registries

- lib/cloudregister/registerutils.py
- tests/test_registercloudguest.py
- tests/test_registerutils.py
- usr/sbin/registercloudguest
The transactional-update command integration was done inside the run_SUSEConnect function as such creating a naming mismatch since the function no longer only called SUSEConnect. Rename the function to a generic name register_product and factor the detection about use of the transactional-update command out into a separate function to be re-used.
> Tidy up transactional-update integration

- cloud-regionsrv-client.changes
- cloud-regionsrv-client.spec
- lib/cloudregister/amazonec2.py
- tests/test_ec2plugin.py
A while back EC2 IMDS gained a "region" endpoint to determine the region in which the instance is running. Using this endpoint directly allows us to drop the code that determined the region based on the information from the "availability-zone" end point. This simplifies the code and testing. Further this is more robust should AWS expand the zone naming as has happened in the past.
> Use the region endpoint of IMDS in EC2

- lib/cloudregister/registerutils.py
The get_hosts() method classifies the IP addresses into ipv4 and ipv6. The way it was done was not quite correct. This commit fixes it.
> Fixed ipv4/ipv6 address detection from string

- cloud-regionsrv-client.changes
- cloud-regionsrv-client.spec
- fix-for-sles12-disable-registry.patch
Addresses various issues related to RPM build for SLE 15 and SLE 12 code streams.
- Fixes a bug (bsc#1230615) with the sudo rule setup, there is a separate issue with conflicting directory ownership, both issues are fixed
- The patch to disable registry related setup did not longer apply in SLE 12, fixed
- Removed registry related files from the SLE 12 package, since we do not support registry setup in SLE 12 these should not be there
- Cleaned up some rpmlint warnings for description length
> Spec clean

- .github/workflows/ci-patch-validation.yml
When we change code this can impact the ability to apply the custom patches that we carry with the package. This commit adds a github action to apply the patches to the changed source to make sure all custom patches still applies.
> Add patch validation per pull request

- cloud-regionsrv-client.changes
- usr/sbin/registercloudguest
LTSS as an add on product has always SLES-LTSS as the product identifier in the product triplet even on other SLE products such as SLES For SAP and SLE HPC. Update the code to reflect this naming oddity.
> Fix LTSS registration

- cloud-regionsrv-client.changes
- cloud-regionsrv-client.spec
cloud-regionsrv-client modifies config files from the container toolchain, docker and podman. These files are provided by packages under certain conditions, e.g. permission and ownership. If the files are not present on the system when registercloudguest is called they are created under the umask() of the calling user which is not neccessarily correct. Because of that, this commit adds a requirement to the respective packages providing the config files such that any modifications retains the permission and ownership.
> Make sure to require container toolchain

- cloud-regionsrv-client.changes
- integration_test-process.txt
- tests/test_registercloudguest.py
- usr/sbin/registercloudguest
suseconnect is changing to write error messages to STDERR instead of STDOUT, as such we need to check both pipes for the error message to avoid having a hard version dependency. Further the error message has changed and we need adjust for this condition as well.
Reference: https://github.com/SUSE/connect-ng/pull/272/files
> Update pipe to check for error message

- .github/workflows/ci-patch-validation.yml
- apply_patches
- cloud-regionsrv-client.spec
- fix-for-sles12-disable-ipv6.patch
- fix-for-sles12-disable-registry.patch
- fix-for-sles12-no-trans_update.patch
Fix patch files such that they apply clean and without producing a .orig file. Anytime a patch gets applied unclean it leaves a .orig file and the package build fails because of a new and unpackaged file. This commit fixes the patch files to apply clean again and also makes them git compliant
> Update patch files to be clean again

- .gitignore
- Makefile
- cloud-regionsrv-client.spec
The %patch macro does not support to call patch such that it does not create .orig files. Under certain conditions patch creates them and this will break the build for files found but not packaged. From my perspective a successfully applied patch even with an offset drift is still acceptable and doesn't have to break the package build process. The way how we maintain the patches for SLE12 will always provide the offset drift as we are constantly working on other parts of the code. If the patch applies is checked via a github action per PR. Thus I believe the proposed patch should be ok.
Find an example build with this change applied here:
* https://build.suse.de/package/show/home:mschaefer/cloud-regionsrv-client
> Fix build with applied patches

- cloud-regionsrv-client.changes
- cloud-regionsrv-client.spec
- lib/cloudregister/registerutils.py
- tests/test_registercloudguest.py
- tests/test_registerutils.py
- usr/sbin/registercloudguest
The simple docker requirement in the spec file of the cloud-regionsrv-client package has turned into a big problem for customers who don't want docker on their systems. This commit makes docker a recommended package and refactors the registration setup code in a way that docker becomes an optional part of the setup procedure. With each call of registercloudguest a check is made to see if docker is installed. If it is installed the current setup is updated with a docker related configuration if not already done
> Turn docker into an optional setup

- cloud-regionsrv-client.changes
- cloud-regionsrv-client.spec
- lib/cloudregister/registerutils.py
- usr/lib/systemd/system/guestregister-lic-watcher.service
- usr/lib/systemd/system/guestregister-lic-watcher.timer
- usr/sbin/cloudguest-lic-watcher
- usr/sbin/registercloudguest
We currently support Azure instances in a transition from PAYG to BYOS and vice-versa. This transition is going to be supported in GCE as well. Therefore create an implementation that is not framework specific and utilizes the flavor determination implemented with the instance-billing-flavor-check.
> Generalize flavor transition

- cloud-regionsrv-client.changes
- usr/sbin/cloudguest-lic-watcher
It is possible that our state file disappears. In this case we need to still handle the state transition between billing flavors correctly. We do not want the user to have to mess withe registration even if our cache disappears.
> Handle state inconsistency

- .github/workflows/ci-testing.yml
ubuntu-20.04 is a deprecated target on the github actions matrix and can no longer be used. We referenced this distro because it was the only one providing the old python 3.6 stack. This commit drops the 3.6 tests and therefore the SLE15 (3.6) testing pipeline. This code also has to support SLE12 (3.4) but we never had a pipeline for that old python versions. So for the future we have to manually make sure the code in this project works for 3.6 and 3.4 or come up with our own github runners.
> Update CI testing action

- lib/cloudregister/smt.py
- tests/test_smt.py
In order to have more information in the logs for debugging purposes,
add info logging when we succeed requesting a cert to the update
infrastructure server
This is related to bsc#1242435
> Explicit confirm cert request

- lib/cloudregister/registerutils.py
Before MLM the SUMA product was named 'SUSE-Manager-Server.prod', 
now it is called 'Multi-Linux-Manager-Server.prod', we need to check both products
This fixes bsc#1243437
> Update SUMA and MLM check

- lib/cloudregister/registerutils.py
- tests/test_registercloudguest.py
- tests/test_registerutils.py
Due to certain conditions, the /etc/hosts file keeps update infrastructure and registry entries when they should be removed
This change fixes bsc#1244152
> Remove entries from /etc/hosts file when cleanup

- lib/cloudregister/registerutils.py
When getting an update infrastructure server and there is a fail over and registration is not completed, we wait the regsharing time to be triggered plus 10 seconds to make sure the credentials are shared and sync'ed between the siblings
This is part of the changes to fix bsc#1242435
> Add delay if registration is not completed during fail over

- cloud-regionsrv-client.changes
- lib/cloudregister/registerutils.py
- tests/test_registerutils.py
Code was not releasable due to untested changes being merged triggering an error when we were checking for access to the network for the IPv6 protocol. One error was that IPAdress objects were passed for socket creation instead of a string and the other error was that we did not pass an address at all.
> Fix code state

- lib/cloudregister/registerutils.py
- tests/test_registerutils.py
Do not fail the registration if the region service is not configured as an IP address. This regression was found with the following valid regionData.cfg from my test infrastructure
```
[region]
public-ips = 10.0.2.100
smt-server-ip = localhost:44300
smt-server-name = localhost:44300
smt-registry-name = registry-example.susecloud.net:44300
smt-fingerprint = ...
```
The proposed patch makes sure that both IP based and name based setup continues to work
> Fix IPv6 check for registration server(s)

- cloud-regionsrv-client.changes
- cloud-regionsrv-client.spec
During install and removal test in the build service the order of dependent packages is non deterministic, this may lead to failures during build. Force the exit condition of preun to be 0 to avoid this non deterministic failure.
> Appease the build service

- integration_test-process.txt
- lib/cloudregister/registerutils.py
- tests/test_registerutils.py
When getting the IP addresses from the region server, we were storing `IPv4Address` and `IPv6Address` types
When we do the socket connection with that it fails
```
connection = socket.create_connection((server_ip, 443), timeout=2)
File "/usr/lib64/python3.4/socket.py", line 498, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
File "/usr/lib64/python3.4/socket.py", line 537, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
TypeError: getaddrinfo() argument 1 must be string or None
```
This Fixes bsc#1247466
> Store IP addresses as str

- cloud-regionsrv-client.changes
- lib/cloudregister/registerutils.py
- usr/lib/zypp/plugins/urlresolver/susecloud
Make the function less expensive on re-use. Previously the function encapsulated the extraction of the root directory from the zypper command line, meaning for every invocation we ended up calling the ps utility. A use case has arisen where we want to re-use the function to find orphaned credetials. In this case zypper is not running and trying to extract the root path becomes and expensive undertaking. With this change the function takes the rtarget root path as an additional argument, which by default is the system root, i.e. /. This pushed the responsibility of getting the target root to the caller. At this point only the urlresolver needs the target root functionality. Further, the urlresolver already has a feature to reduce the redundant calls when we are in the same zypper process …
> Modify the credentials_files_are_equal interface

- integration_test-process.txt
- lib/cloudregister/registerutils.py
- tests/test_registercloudguest.py
- tests/test_registerutils.py
-  update the uses of os.path.join to use either os.sep.join or
os.path.normpath with os.sep.join to avoid oddities of th path.join
implementation if the second argument starts with a /. While we have not
had problems with this so far the previous use of path.join required
careful setu of constants and processing when files are being used. Also
discovered 1 incorrect use of path.join() and found another case where
string concatenation was used.
- Add clarifying note to separate command that should be run on SLE 15 or later
and commands that only apply to SLE 12. Also clean up after changes introduced
with 1faefb5e66
> Consist path merge

- cloudregister/registercloudguest.py
- cloudregister/registerutils.py
- test/unit/registerutils_test.py
Another version in code to handle the transition from http based repo urls to resolver based urls was found and can be dropped because the transition period is over. This Fixes #185 and is related to bsc#1245370
> Drop obsolete switchcloudguestservices.py take two

- Makefile
The Makefile looked up the version information by calling a small python script that imports the version information from source. This required to lookup the python interpreter from the host which can be avoided now that we use poetry for development. This commit moves the creation of the version variable to the target where it is needed and uses "poetry run python" to obtain the version information.
> Fix Makefile package target
